### ISSUE TITLE
Can't run the node.js server

### ISSUE THREAD

**Issue by tomersagi** [Minitour/BigDataHW4#10]
This is the error message:

```bash
$ node modules/iex/app.js 
/home/tomer/Teaching/BigDataMgt/BigDataHW4Tonyetal/modules/iex/app.js:32
            let objc = JSON.parse(data)
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by Minitour** [comment]
I forgot to add the “npm install” command.
CD to the iex directory and run “npm install”.
Should work after that.

**Comment by tomersagi** [comment]
And you forgot to add that you need to install nodejs and npm on the machine.

**Comment by Minitour** [comment]
Yeah that too... my bad  

https://nodejs.org/en/download/

`npm` comes with `nodejs` pre-packaged.

**Comment by Minitour** [comment]
Might as well let you know you should also install the following python libs:
```
pip install bs4 
pip install flask 
pip install nltk
pip install pyspark
pip install requests 
pip install requests_oauthlib 
pip install sklearn
```

**Comment by tomersagi** [comment]
ok, fixed
